language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-24
  - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.0
  - android-24
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
- "./gradlew build assembleDebug"
- mv ./
deploy:
  provider: releases
  api_key:
    secure: HNWFRDzt1cVifIGkEm9fFiFX8E2Sr2cfDTXk2mehdji2atYH1LJaU3r6ydF8L/V2qwSAZECj7SIIvQqFXsWHbWFazTD/ln7yuA0aqQXayx6qiNmEVnd/uvXqGpKgGHoJgkaZN31kJu9VqigmGXJ7HuRJVeZoYeBpQ3N0ltXuUsovjbkPNUt0VULYH3pYpJRYsvek4/L0Fi1ZPPM/iKfujY9oeVoOsK+h9HAXqdMDXvKJTl++ff2lwaveHaZm298F8goUn7N87rDxmqIiVEPZdM617g2rfNHGaR8uDW6ot+IfvyiXj2VxypLslgWyuh2bK6vYXMBu4jPSkNt7nLW57wfxR7xJfJbcueVM9ywaXXFcn1NYptlYERIepo9FXTzD+EGjBJxi3rDOwp20NiJO6zWFuL2OgEzHKfgXvnfppLEGDYisxIU0JZOrtUGBdd6Co/1YyL9BeLpA8ES3IB3Ec91DjOm4N91geo3qo9ZauC2mvs2ugN1rGuM0SxQNdaKHj3bWjGwGBOtOtSJqtWQGEuk4GuHdIlqby6I+Isz3EyMWNwWGnjCze3rtJGjHxkHY0/69CNhgEvw1gTkXexgp18o+3aUURNc6A5LWc6nQhYMeG3EMJxMIbJB2tfnGjV6fhxefBBwRa9qVIDeTKhmWumotOEbVdmE+hmv5MoDxsZg=
  file: "/app/build/outputs/apk/app-debug-*.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    repo: LionZXY/BMSTUWiFi
    branch: developers
