language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.0
  - android-24
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew build